### ISSUE TITLE
list_system_summary(organization)

### ISSUE THREAD

**Issue by welpdx** [rafaelfoster/FortiEDR_API#4]
Following example.py
When trying to run admin_data = admin.list_system_summary(organization)
I get response

```
Error on defined params!
Param 'addLicenseBlob' should be defined as type 'bool', not <class 'str'>
```

**Comment by rafaelfoster** [comment]
Hi @welpdx,

Thanks for raising this issue. It was an error, as function positions have been reorganized.

The below code might work for you:
`admin_data = admin.list_system_summary(organization=organization)`

Please let me know if that works.

RF

**Comment by welpdx** [comment]
Hi @rafaelfoster, 
Thanks for the quick response!
Your suggestion does work. Thank you!
I was also reading fortinet.py and realized that I can also do

```
licenseBlobNo = False
admin_data = admin.list_system_summary(licenseBlobNo,organization)
```

Thank you and thanks for this repo.
